import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Wrapper from "@/components/wrapper/Wrapper";

const inter = Inter({
  subsets: ["latin"],
  weight: ["200", "400", "700"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Deluxe Mods",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body>
        <Navbar />
        <main className="flex-1 flex justify-center bg-[var(--background-gray-3)]">
          <Wrapper>{children}</Wrapper>
        </main>
        <Footer />
      </body>
    </html>
  );
}
